language: ruby
rvm:
    - 2.3.3

before_script:
    - chmod +x ./script/cibuild

script:
    ./script/cibuild

env:
    global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installtion of html-proofer

sudo: false
